# MagedIn - Magento DockerLab
# (https://github.com/magedin/magento-dockerlab)
version: "3"

services:
  php:
    image: magedin/php:7.2-fpm-buster
    container_name: econocargo_php
    user: www
    volumes:
      - ~/.composer:/var/www/.composer:cached
      - ./:/var/www/html
