# MagedIn - Magento DockerLab
# (https://github.com/magedin/magento-dockerlab)
version: "3"

services:
  php:
    image: php:7.1-fpm-buster
    container_name: econocargo_php
    volumes:
      - ~/.composer:/var/www/.composer:cached
      - ./:/var/www/html
